Pizzeria/urls.py
from django.contrib import admin
from django.urls import path,include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pizzas.urls')),
]

pizzas/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'pizzas'

urlpatterns = [
    path('',views.index, name='index'),
    path('pizza_options',views.pizza_options, name='pizza_options'),
    path('pizza_options/<int:pizza_id>/',views.pizza, name ='pizza'),
    path('comments/<int:pizza_id>/',views.comments, name='comments'),
    path('picture', views.pizza, name="picture"),
    
]

pizzas/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Pizza(models.Model):
    pizza_name = models.CharField(max_length=200)
    image = models.ImageField(upload_to="images/")

    def __str__(self):
        return self.pizza_name


class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping_name = models.CharField(max_length=200)

    def __str__(self):
        return self.topping_name

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    comment = models.TextField(max_length=200)
    
    def __str__(self):
        return self.comment

pizzas/forms.py
from django import forms

from .models import *

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']
        labels = {'comment':''}

        

pizzas/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.template import loader
# Create your views here.
def index(request):
    return render(request, 'pizzas/index.html')

def pizza_options(request):
    pizza_options = Pizza.objects.filter().order_by()

    context = {'pizza_options':pizza_options}
    return render(request, 'pizzas/pizza_options.html', context)

def pizza(request,pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)

    toppings = Topping.objects.filter(pizza=pizza)
    comment = pizza.comment_set.all()

    context = {'pizza':pizza, 'toppings':toppings, 'comment':comment}
        
    return render(request, 'pizzas/pizza.html', context)

def toppings(request, topping_id,pizza_id):
    toppings = Topping.objects.get(id=topping_id)
    pizza = Pizza.objects.get(id=pizza_id)

    context = {'toppings':toppings,'pizza':pizza}
    return render(request, 'pizzas/pizza.html', context)

def comments(request,pizza_id):    
    pizza = Pizza.objects.get(id=pizza_id)

    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)

        if form.is_valid():
            comments = form.save(commit=False)
            comments.pizza = pizza
            comments.save()
            
            return redirect('pizzas:pizza', pizza_id=pizza_id)

    context = {'form':form, 'pizza':pizza}
    return render(request, 'pizzas/comments.html', context)

pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Pizzeria</a>
    <a href="{% url 'pizzas:pizza_options' %}">Pizzas</a>
</p>

{% block content %}

{% endblock content %}

pizzas/templates/pizzas/comments.html
{% extends "pizzas/base.html" %}

{% block content %}

<p><a href="{% url 'pizzas:pizza' pizza.id %}">{{pizza}}</a></p>

<p> Add a comment </p>

<form action="{% url 'pizzas:comments' pizza.id %}" method="post">
    {% csrf_token %}

    {{form.as_p}}

    <button name="submit">Add comment</button>
</form>

{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}
{% load static %}
{% block content %}

<p> Alex's Pizzeria </p>

<body> Come check out our Pizzas!

</body>
<img src="{% static 'pizzas/images/pizzahome.png' %}">


{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}
{% load static %}
{% block content %}

<p> Pizza: {{ pizza }} </p>

<div>
     <img src="{{ pizza.image.url }}" width = 400 height=auto/>
</div>

<ul>
     {% for t in toppings %}

     <li> {{ t.topping_name }} </li>

     {% empty %}
     <li> There are no toppings for this pizza </li>
     {% endfor %}
</ul>

<a href="{% url 'pizzas:comments' pizza.id %}">Add comment</a>

<ul>
     {% for c in comment %}
     <li> {{ c }}</li>

     {% empty %}
     <li>No comments have been added.</li>
     {% endfor %}
</ul>

{% endblock content %}

pizzas/templates/pizzas/pizza_options.html
{% extends "pizzas/base.html" %}

{% block content %}

<p> Pizza Options </p>

<ul>
     {% for pizza in pizza_options %}

     <li> 
          <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza.pizza_name }} </a>
     </li>
     {% empty %}
     <li> No pizzas have been added yet </li>
     {% endfor %}

</ul>

{% endblock content %}